// Pre-generated demo content for the Luke 11 sermon
// In production, this would be generated by the AI pipeline

export const DEMO_SERMON_DATA = {
  id: "demo-luke-11",
  title: "The God Who Sees the Inside",
  scripture: "Luke 11:37-54",
  status: "ready",
  progress: 100,
  currentStep: "Complete",
  createdAt: "2026-03-07T00:00:00Z",
  summary: "Jesus dines with Pharisees and exposes the difference between outward religious performance and genuine heart transformation. He pronounces woes on those who clean the outside while neglecting justice, love, and truth on the inside.",
  keyThemes: ["Inside vs. Outside", "Grace and Forgiveness", "True Holiness", "Jesus Confronts the Comfortable"],
  scenes: [
    {
      title: "An Unexpected Dinner Guest",
      content: "A Pharisee invited Jesus to dinner. In those days, sharing a meal was a big deal. But this wasn't a friendly invitation. The Pharisees wanted to watch Jesus closely and find something wrong with him. Jesus knew this, and he went anyway.",
      scriptureRef: "Luke 11:37",
      keyPoint: "Jesus shows up even for people who don't understand him.",
      emotion: "curiosity",
      imagePrompt: "Warm watercolor illustration of a biblical dinner scene. A kind-looking man (Jesus) entering through an arched doorway into a low-lit dining room. Several well-dressed men in robes sit around a low table laden with bread and fruit. Warm golden lamplight. Soft earth tones with touches of teal and amber. Child-friendly, gentle style. No text.",
      animationHint: "zoom-in",
      narratives: {
        young: "Jesus went to eat dinner at a man's house. The man wanted to watch Jesus very carefully. But Jesus wasn't scared. He went because he cared about everyone, even people who didn't like him.",
        older: "A Pharisee invited Jesus over for a meal. But it wasn't really a friendly dinner. The Pharisees wanted to keep an eye on Jesus and catch him doing something wrong. Jesus knew this, but he went anyway. He always shows up for people, even when they don't understand him.",
        family: "Jesus accepted a dinner invitation from a Pharisee, even knowing it was more of an investigation than a friendship. The Pharisees were the religious professionals of the day. They kept every rule and looked good doing it. But Jesus wasn't intimidated by their status. He walked into that room knowing they wanted to trap him, and he went anyway because his mission was to reach everyone, including the comfortable and the powerful."
      },
      quiz: {
        questions: [
          { question: "Why did Jesus go to the Pharisee's house?", options: ["He was hungry", "He cared about everyone", "He was lost"], correctIndex: 1, explanation: "Jesus went because he cares about all people, even those who don't understand him!", ageGroup: "young" },
          { question: "Was the Pharisee's invitation friendly?", options: ["Yes, they were best friends", "No, they wanted to watch Jesus", "They didn't care"], correctIndex: 1, explanation: "The Pharisees wanted to watch Jesus closely and find something wrong with him.", ageGroup: "young" },
          { question: "What were the Pharisees known for?", options: ["Breaking all the rules", "Following religious rules very carefully", "Being farmers"], correctIndex: 1, explanation: "Pharisees were religious leaders who followed every rule very carefully.", ageGroup: "older" },
          { question: "What does it say about Jesus that he went to dinner with people who didn't like him?", options: ["He didn't know they were against him", "He wanted to argue", "He wanted to reach everyone with his message"], correctIndex: 2, explanation: "Jesus showed courage and love by going to people who opposed him.", ageGroup: "older" },
          { question: "What does Jesus' willingness to dine with his opponents teach us about approaching difficult relationships?", options: ["Avoid people who disagree with you", "Show up with courage and love, even when it's uncomfortable", "Only spend time with friends"], correctIndex: 1, explanation: "Jesus models that we can engage with difficult people while maintaining our integrity and love.", ageGroup: "family" },
          { question: "The Pharisees were the 'religious professionals.' What danger does religious expertise carry?", options: ["It always leads to pride", "It can become about performance instead of genuine relationship with God", "There is no danger"], correctIndex: 1, explanation: "Knowledge of God's word is good, but when it becomes about looking right rather than being transformed, it misses the point.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "Have you ever gone somewhere even though you were a little nervous? What made you brave enough to go?", parentTip: "Share your own story of doing something brave. Kids connect with personal examples.", connectionToLife: "Jesus shows us that love sometimes means showing up in uncomfortable places." },
          { question: "Why do you think Jesus cared about people who didn't like him?", parentTip: "Help your child see that loving difficult people is part of following Jesus.", connectionToLife: "We can practice this at school, work, or in our neighborhoods." },
        ]
      },
    },
    {
      title: "The Missing Hand Wash",
      content: "When Jesus sat down to eat, he didn't wash his hands in the special religious way that the Pharisees expected. This wasn't about germs. It was a religious ceremony that the Pharisees had added to God's law. And when Jesus skipped it, they were shocked.",
      scriptureRef: "Luke 11:38",
      keyPoint: "Jesus challenges man-made rules that miss God's heart.",
      emotion: "surprise",
      imagePrompt: "Warm watercolor illustration of a biblical dining scene. A man (Jesus) sits calmly at a low table while other men in elaborate robes look shocked, with wide eyes and raised eyebrows. A decorative washing basin sits unused nearby. Warm amber and teal tones. Soft, child-friendly style. No text.",
      animationHint: "pan-left",
      narratives: {
        young: "When Jesus sat down to eat, he didn't wash his hands the special way the other men expected. They were really surprised! But Jesus wanted to show them that what's in your heart is more important than following extra rules.",
        older: "The Pharisees had lots of extra rules that they added to what God actually said. One rule was about washing hands in a special religious way before meals. When Jesus sat down without doing this, they were shocked. But Jesus wasn't being rude. He was making a point: God cares more about what's inside your heart than outside rituals.",
        family: "The hand-washing ritual wasn't about hygiene. It was a tradition the Pharisees had elevated to the level of God's command. By skipping it, Jesus was doing something deliberate. He was exposing the difference between man-made religion and God's actual priorities. The Pharisees had built an entire system of external compliance, and Jesus walked right through it."
      },
      quiz: {
        questions: [
          { question: "Did Jesus forget to wash his hands?", options: ["Yes, he forgot", "No, he did it on purpose", "He doesn't have hands"], correctIndex: 1, explanation: "Jesus skipped it on purpose to teach an important lesson!", ageGroup: "young" },
          { question: "What matters more to God?", options: ["How clean your hands are", "What's in your heart", "What clothes you wear"], correctIndex: 1, explanation: "God cares most about what's inside us, our heart!", ageGroup: "young" },
          { question: "Why were the Pharisees shocked?", options: ["Jesus broke a religious tradition", "Jesus spilled his drink", "Jesus was late"], correctIndex: 0, explanation: "Jesus didn't follow their extra rules, and they couldn't believe it.", ageGroup: "older" },
          { question: "What's the difference between God's commands and the Pharisees' extra rules?", options: ["There's no difference", "God's commands come from love; the extra rules were about control", "The extra rules were better"], correctIndex: 1, explanation: "God's real rules are about love. The Pharisees added rules to show off and control others.", ageGroup: "older" },
          { question: "What 'extra rules' might we follow today that aren't actually from God?", options: ["All church traditions are wrong", "Sometimes we confuse cultural expectations with God's commands", "Rules don't matter at all"], correctIndex: 1, explanation: "It's worth examining whether our religious habits are truly from God or just comfortable traditions.", ageGroup: "family" },
          { question: "How do we tell the difference between God's actual priorities and human-added religion?", options: ["We can't tell", "By looking at whether the rule leads to more love or more judgment", "Ask a Pharisee"], correctIndex: 1, explanation: "God's commands always lead toward love, justice, and mercy. Human additions often lead toward pride and exclusion.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "Can you think of a rule that people follow just because 'that's how it's always been done,' even if it doesn't really help anyone?", parentTip: "Think of examples from your own family or workplace routines.", connectionToLife: "Sometimes we hold onto habits without asking if they actually matter to God." },
          { question: "What do you think God cares about more: how things look on the outside, or what's really going on inside?", parentTip: "Use a simple illustration: a beautifully wrapped empty box vs. a plain box full of something wonderful.", connectionToLife: "This applies to how we treat people, how we worship, and how we live." },
        ]
      },
    },
    {
      title: "Clean Cup, Dirty Heart",
      content: "Jesus said something that really got their attention: 'You Pharisees clean the outside of the cup and dish, but inside you are full of greed and wickedness.' He used a picture they could understand: a cup that looks shiny on the outside but is filthy on the inside.",
      scriptureRef: "Luke 11:39-40",
      keyPoint: "God sees what's really inside us, not just what we show the world.",
      emotion: "conviction",
      imagePrompt: "Warm watercolor illustration showing two cups side by side. One cup is beautifully polished and shiny on the outside but dark and dirty inside. The other cup is simple but clean and glowing inside with warm light. Teal and amber color palette. Soft, dreamy watercolor style suitable for children. No text.",
      animationHint: "zoom-in",
      narratives: {
        young: "Jesus talked about a cup. Imagine a cup that looks really clean and sparkly on the outside, but inside it's all yucky and dirty. Would you want to drink from that cup? Jesus said some people are like that cup. They look good on the outside, but inside, their hearts aren't clean.",
        older: "Jesus used a picture everyone could understand: a cup. He said the Pharisees were like a cup that's been polished until it shines on the outside, but if you looked inside, it was still dirty. They spent all their energy looking good to others but forgot to clean up what really matters: their hearts. God doesn't just see what we show the world. He sees everything inside us.",
        family: "This is the core image of the sermon. Jesus' metaphor of the cup cuts through all religious pretense. The Pharisees had mastered external compliance: they tithed precisely, they dressed right, they knew every law. But Jesus says none of that matters if the inside is full of greed and wickedness. It's a direct challenge to anyone who has ever confused 'looking like a Christian' with actually being transformed by Christ."
      },
      quiz: {
        questions: [
          { question: "What did Jesus compare the Pharisees to?", options: ["A dirty cup", "A shiny cup that's dirty inside", "A broken plate"], correctIndex: 1, explanation: "Jesus said they were like a cup that looks clean outside but is dirty inside!", ageGroup: "young" },
          { question: "Does God only see the outside of us?", options: ["Yes, just what we show", "No, God sees our hearts too", "God doesn't look at us"], correctIndex: 1, explanation: "God sees everything about us, including what's in our hearts!", ageGroup: "young" },
          { question: "What does the 'inside of the cup' represent?", options: ["Our clothes", "Our heart and true self", "Our house"], correctIndex: 1, explanation: "The inside of the cup represents what we're really like on the inside, our thoughts, feelings, and true motivations.", ageGroup: "older" },
          { question: "Why is it easier to 'clean the outside' than the inside?", options: ["Outside cleaning is visible to others", "Inside cleaning is impossible", "God only cares about the outside"], correctIndex: 0, explanation: "It's easier to look good to others than to truly change our hearts. But God sees both.", ageGroup: "older" },
          { question: "In what ways might we 'polish the outside of our cup' while neglecting the inside?", options: ["By attending church but not practicing love at home", "By reading the Bible daily", "By praying sincerely"], correctIndex: 0, explanation: "Religious activities are good, but they can become a substitute for genuine heart change if we're not careful.", ageGroup: "family" },
          { question: "How do we 'clean the inside'?", options: ["By trying harder to be good", "By being honest with God about our failures and accepting his grace", "By hiding our faults"], correctIndex: 1, explanation: "Inner transformation comes through honesty with God, repentance, and trusting in his grace, not through more performance.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "If God could see inside your heart right now, what would he find? Don't worry, there's no wrong answer.", parentTip: "Go first. Share something honest from your own heart. Vulnerability invites vulnerability.", connectionToLife: "This teaches kids that it's safe to be honest about their struggles." },
          { question: "What does it look like to 'clean the inside' of our lives? Is it different from cleaning the outside?", parentTip: "Help kids understand that being honest with God is more important than just following rules.", connectionToLife: "Confession, honesty, and asking for help are how we start to change from the inside out." },
        ]
      },
    },
    {
      title: "Missing What Matters Most",
      content: "Jesus told the Pharisees they carefully tithed their tiny herbs and spices, measuring out exactly ten percent of their mint and rue plants. But they completely ignored justice and the love of God. They checked all the little boxes but missed the big picture.",
      scriptureRef: "Luke 11:42",
      keyPoint: "Don't get so caught up in small religious details that you miss justice and love.",
      emotion: "sadness",
      imagePrompt: "Warm watercolor illustration of a man carefully measuring tiny herbs on a small scale, while behind him through a window, people are in need reaching out for help. The man doesn't see them. Warm earth tones with teal accents. Soft, child-friendly watercolor style. No text.",
      animationHint: "pan-right",
      narratives: {
        young: "The Pharisees were very careful about small things. They even counted their tiny little plants to make sure they gave God exactly the right amount. But they forgot about the big things, like being kind and loving people! It's like making sure your shoelaces are perfectly tied while your friend is crying and needs a hug.",
        older: "Imagine someone who spends hours making sure every pencil on their desk is perfectly straight, but they never help anyone with their homework. That's what the Pharisees were doing. They measured out exactly one-tenth of their herbs for God, but they walked right past people who needed justice and love. Jesus said, 'You should have done the big things without leaving the small things undone.'",
        family: "The Pharisees' meticulous tithing of herbs wasn't wrong in itself. Jesus even says they should have done it. The problem was proportion. They gave enormous attention to tiny details of religious compliance while completely ignoring the weightier matters of the law: justice and love. This is a warning for anyone who finds it easier to follow religious routines than to actually love their neighbors sacrificially."
      },
      quiz: {
        questions: [
          { question: "What did the Pharisees carefully measure?", options: ["Their food", "Their tiny herbs for God", "Their money"], correctIndex: 1, explanation: "They measured even their smallest plants to make sure they gave God the right amount!", ageGroup: "young" },
          { question: "What did they forget about?", options: ["Their lunch", "Being kind and loving people", "Their hats"], correctIndex: 1, explanation: "They forgot about the most important things: justice and love!", ageGroup: "young" },
          { question: "Jesus said the Pharisees neglected 'justice and the love of God.' What does that mean?", options: ["They didn't go to church", "They didn't care about treating people fairly or loving God genuinely", "They didn't pray enough"], correctIndex: 1, explanation: "Justice means treating people fairly, and love of God means genuinely caring about what God cares about, not just following rules.", ageGroup: "older" },
          { question: "Can someone follow all the rules and still miss what God really wants?", options: ["No, following rules is enough", "Yes, if they do it without love", "Rules don't matter"], correctIndex: 1, explanation: "God wants our hearts, not just our compliance. Following rules without love misses the point.", ageGroup: "older" },
          { question: "What 'small things' might we focus on in our faith while missing the 'big things'?", options: ["All religious practices are small things", "Things like church attendance or Bible reading can become substitutes for actually loving people", "There are no big things"], correctIndex: 1, explanation: "The goal isn't to stop the small practices, but to make sure they serve the bigger purposes of justice and love.", ageGroup: "family" },
          { question: "How do we hold onto both the details and the big picture of faith?", options: ["Focus only on love", "Let the big commands (love God, love neighbor) shape how we do the small things", "Focus only on rules"], correctIndex: 1, explanation: "When love drives our religious practice, the small things find their proper place.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "Can you think of a time when you focused on something small and missed something bigger that really mattered?", parentTip: "Use an everyday example: cleaning your room perfectly but ignoring your sibling who needed help.", connectionToLife: "God wants us to notice what really matters: people and love." },
          { question: "What are the 'big things' God cares about most?", parentTip: "Guide toward: loving God, loving people, fairness, kindness, mercy.", connectionToLife: "When we focus on these, the smaller things fall into place naturally." },
        ]
      },
    },
    {
      title: "Heavy Burdens, No Help",
      content: "Then Jesus turned to the lawyers, the legal experts of the law. He said they loaded people down with impossible burdens and rules but wouldn't lift a finger to help anyone carry the load. They used God's Word as a weapon instead of a comfort.",
      scriptureRef: "Luke 11:46",
      keyPoint: "Faith should lift people up, not weigh them down.",
      emotion: "compassion",
      imagePrompt: "Warm watercolor illustration showing a person struggling under a huge stack of heavy scrolls and books, bending under the weight. Nearby, well-dressed men watch with crossed arms, not helping. In the background, a gentle figure (Jesus) reaches out a hand to help. Warm amber light, teal and earth tones. Child-friendly style. No text.",
      animationHint: "zoom-out",
      narratives: {
        young: "Some people were carrying really heavy things on their backs, so many rules and things they had to remember. And the leaders just stood and watched. They didn't help at all! But Jesus saw this and said, 'That's not right. I came to help you carry that.'",
        older: "The religious lawyers had turned God's Word into an impossible list of rules. They piled requirements on ordinary people until the burden was crushing. But here's what made Jesus angry: the lawyers themselves wouldn't lift a finger to help. They stood with their arms crossed while people struggled. Jesus said faith should help people, not crush them.",
        family: "This is one of the most heartbreaking woes. The legal experts had taken God's life-giving Word and weaponized it. They created a maze of requirements so tangled that no one could navigate it alone. And then they stood back and watched people fail. The phrase that stings most: 'You yourselves do not touch the burdens with one of your fingers.' They demanded perfection from others while offering no grace, no help, and no compassion."
      },
      quiz: {
        questions: [
          { question: "Did the leaders help people carry their heavy loads?", options: ["Yes, they helped a lot", "No, they just watched", "They carried everything"], correctIndex: 1, explanation: "The leaders didn't help at all! They just stood and watched.", ageGroup: "young" },
          { question: "What did Jesus think about this?", options: ["He liked it", "He thought it was wrong", "He didn't notice"], correctIndex: 1, explanation: "Jesus said it was wrong to give people heavy burdens and not help them!", ageGroup: "young" },
          { question: "What does it mean to 'load people with burdens hard to bear'?", options: ["Give them heavy boxes", "Create impossible standards and judge people who can't meet them", "Help them exercise"], correctIndex: 1, explanation: "It means setting rules so impossible that no one can follow them, then judging people for failing.", ageGroup: "older" },
          { question: "How should faith leaders treat people?", options: ["Make things harder", "Help people grow with grace and support", "Ignore them"], correctIndex: 1, explanation: "Good leaders help carry people's burdens, just like Jesus does for us.", ageGroup: "older" },
          { question: "Have you ever felt crushed by religious expectations? How does Jesus' response here change that?", options: ["Jesus adds more rules", "Jesus calls out those who burden others and offers to help carry the load himself", "Jesus doesn't care"], correctIndex: 1, explanation: "Jesus stands against using faith as a weapon. He came to give rest, not more burdens.", ageGroup: "family" },
          { question: "How can we avoid becoming like the lawyers, creating burdens for others in our communities?", options: ["Don't teach the Bible", "Lead with grace and be willing to help, not just demand", "Lower all standards"], correctIndex: 1, explanation: "The goal is not to abandon truth but to carry it with grace and to help others instead of judging from a distance.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "Has anyone ever expected something really hard from you but didn't help you do it? How did that feel?", parentTip: "Validate the feeling. Then connect it to how God is different: he helps us.", connectionToLife: "Jesus said 'Come to me, all who are weary and heavy-laden.' He helps us carry our loads." },
          { question: "How can we be people who help others instead of making things harder for them?", parentTip: "Brainstorm specific, practical ways as a family.", connectionToLife: "At school, at work, in our neighborhood, we can lift people up instead of weighing them down." },
        ]
      },
    },
    {
      title: "The Key That Was Locked Away",
      content: "The strongest thing Jesus said was this: 'Woe to you lawyers, for you have taken away the key of knowledge. You did not enter yourselves, and you hindered those who were entering.' They had the key to knowing God, and they locked the door and threw it away.",
      scriptureRef: "Luke 11:52",
      keyPoint: "No one should stand between people and God's love.",
      emotion: "urgency",
      imagePrompt: "Warm watercolor illustration of a large golden key lying on the ground in front of a closed ornate door. Behind the door, warm golden light shines through the cracks. A child reaches toward the key while robed figures stand blocking the path. Teal, gold, and warm earth tones. Dreamy, child-friendly style. No text.",
      animationHint: "zoom-in",
      narratives: {
        young: "Imagine there's a beautiful door with something wonderful behind it. And you have the key! But instead of opening the door for everyone, the leaders hid the key. They didn't go through the door themselves, and they stopped other people from going through too. Jesus said, 'That's the worst thing you could do.'",
        older: "The lawyers had something precious: the knowledge of God. They studied the Scriptures every day. They knew the way to God. But instead of sharing that knowledge and helping people find God, they locked the door and stood in front of it. They didn't enter themselves, and they stopped others from entering. Jesus said this was the worst of all their failures.",
        family: "This is the most devastating accusation in the passage. The religious experts possessed the very thing people needed most: the key to knowing God. And they did two unforgivable things with it. First, they refused to use it themselves, choosing religious performance over genuine relationship with God. Second, and worse, they actively prevented others from finding God. They took the most beautiful invitation in the universe and turned it into a locked gate."
      },
      quiz: {
        questions: [
          { question: "What did the leaders do with the key to knowing God?", options: ["They shared it", "They hid it away", "They ate it"], correctIndex: 1, explanation: "They kept the key to knowing God all to themselves and wouldn't let others in!", ageGroup: "young" },
          { question: "What should they have done?", options: ["Hidden the key better", "Opened the door for everyone", "Nothing"], correctIndex: 1, explanation: "They should have used the key to help everyone find God!", ageGroup: "young" },
          { question: "What is the 'key of knowledge'?", options: ["A golden key", "Understanding of God's Word and the way to God", "A school test"], correctIndex: 1, explanation: "The key of knowledge is understanding God's Word and helping people know God personally.", ageGroup: "older" },
          { question: "Why did Jesus say this was the worst thing?", options: ["Because keys are expensive", "Because they stopped people from finding God", "Because he likes doors"], correctIndex: 1, explanation: "Standing between people and God is the most serious failure of all.", ageGroup: "older" },
          { question: "In what ways can religious institutions or individuals today 'take away the key of knowledge'?", options: ["By making faith seem exclusive", "By making God's love inaccessible through complexity, judgment, or gatekeeping", "It can't happen today"], correctIndex: 1, explanation: "Anytime we make knowing God harder than it needs to be, or block people from experiencing grace, we repeat this pattern.", ageGroup: "family" },
          { question: "How can we be 'door openers' for others?", options: ["By being judgmental", "By sharing God's love simply and inviting people in", "By keeping faith private"], correctIndex: 1, explanation: "We open the door by living out grace, being welcoming, and making the gospel accessible.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "What would you do if you found a key that could open a door to something amazing? Would you share it or keep it?", parentTip: "Use this as a bridge: God's love is the amazing thing behind the door, and we get to share it.", connectionToLife: "We can be people who open doors for others, not lock them." },
          { question: "Has anyone ever helped you understand something about God that you didn't get before? How did that feel?", parentTip: "Share your own story of someone who helped you understand faith.", connectionToLife: "We all need someone to hand us the key. We can be that person for others." },
        ]
      },
    },
    {
      title: "Jesus Moves Toward the Cross",
      content: "After all these hard things, the Pharisees and lawyers began to press Jesus hard, trying to trap him. They wanted to use his own words against him. But Jesus wasn't afraid. He kept teaching. He kept walking toward Jerusalem, toward the cross. The same God who confronted the comfortable would die for everyone.",
      scriptureRef: "Luke 11:53-54",
      keyPoint: "Jesus' confrontation is never cruelty; it is always compassion leading to the cross.",
      emotion: "hope",
      imagePrompt: "Warm watercolor illustration of a figure (Jesus) walking calmly down a sunlit path toward a distant city on a hill (Jerusalem). Behind him, shadows of men pointing and arguing. But the figure walks with peace and purpose, bathed in warm golden light. Teal sky, amber sunset, warm earth tones. Hopeful, child-friendly style. No text.",
      animationHint: "pan-right",
      narratives: {
        young: "After Jesus said all those hard things, the leaders got really mad. They tried to trick him and catch him saying something wrong. But Jesus wasn't afraid. He kept going. He kept loving. He was walking to a place where he would show the biggest love of all.",
        older: "The Pharisees and lawyers were furious. They started pressing Jesus with hard questions, trying to trap him. They were plotting against him. But here's the amazing thing: Jesus knew what they were planning, and he didn't run. He kept teaching. He kept walking toward Jerusalem. He was heading to the cross, where he would die, not just for the sinners on the margins, but even for the Pharisees who were plotting against him.",
        family: "This is where the sermon comes together. The same Jesus who spoke these hard truths at the dinner table is the same Jesus who would die on the cross for everyone in that room. His confrontation was never cruelty. It was compassion. He confronted the Pharisees not to destroy them but to wake them up. And even as they plotted to kill him, he walked willingly toward the cross. He died for the sinners who knew they were broken, and for the religious leaders who didn't. That's the God of the inside: the one who sees everything and loves anyway."
      },
      quiz: {
        questions: [
          { question: "Was Jesus scared when the leaders got angry?", options: ["Yes, very scared", "No, he kept going", "He ran away"], correctIndex: 1, explanation: "Jesus was brave! He kept going because he loved everyone.", ageGroup: "young" },
          { question: "Where was Jesus walking to?", options: ["Home", "Jerusalem, where he would die for us", "The store"], correctIndex: 1, explanation: "Jesus was walking to Jerusalem, where he would show the biggest love ever by dying for us.", ageGroup: "young" },
          { question: "Why did Jesus confront the Pharisees if he knew they'd turn against him?", options: ["He was angry", "He wanted to help them see the truth, even at great cost", "He didn't know"], correctIndex: 1, explanation: "Jesus confronted them because he loved them and wanted them to change, even though it would cost him everything.", ageGroup: "older" },
          { question: "Who did Jesus die for?", options: ["Only good people", "Only sinners", "Everyone: sinners, Pharisees, all of us"], correctIndex: 2, explanation: "Jesus died for everyone. That's the beauty of the gospel.", ageGroup: "older" },
          { question: "What does it mean that Jesus' confrontation was 'compassion, not cruelty'?", options: ["He was being mean", "Hard truth spoken in love is an act of care, not punishment", "He didn't care about feelings"], correctIndex: 1, explanation: "When Jesus speaks hard truth, it's because he loves us too much to leave us where we are.", ageGroup: "family" },
          { question: "How does knowing Jesus died even for those who rejected him change how we view difficult people?", options: ["It doesn't change anything", "If Jesus loved his enemies to the point of death, we can extend grace to those who frustrate us", "We should avoid them"], correctIndex: 1, explanation: "The cross is the ultimate expression of grace extended to the undeserving. We were all undeserving.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "Jesus kept loving people even when they were mean to him. When is it hardest for you to keep being kind?", parentTip: "Affirm that it's hard! Then remind them that Jesus gives us the power to love even when it's difficult.", connectionToLife: "We can ask God for help to love people even when it's really hard." },
          { question: "The sermon says Jesus 'sees everything and loves anyway.' How does that make you feel?", parentTip: "Let each family member respond. This is a core truth that can reshape how we see God.", connectionToLife: "Nothing we've done or thought is hidden from God, and he loves us completely anyway." },
        ]
      },
    },
    {
      title: "Changed from the Inside Out",
      content: "The sermon ended with a story about a college student whose hidden sins were exposed, but instead of running, he repented. He went back to the people he'd hurt and asked for forgiveness. That act of genuine repentance drew another person to Christ. Real change doesn't come from polishing the outside. It comes from letting God transform the inside.",
      scriptureRef: "",
      keyPoint: "Genuine repentance and grace are more transformative than any amount of religious performance.",
      emotion: "transformation",
      imagePrompt: "Warm watercolor illustration of a person kneeling with hands open, surrounded by warm golden light breaking through clouds. The scene transitions from dark shadows on one side to bright, colorful flowers blooming on the other, symbolizing inner transformation. Teal, amber, and gentle greens. Hopeful, child-friendly watercolor style. No text.",
      animationHint: "fade",
      narratives: {
        young: "Sometimes we do wrong things and we try to hide them. But when we say 'I'm sorry' and really mean it, something amazing happens. God helps us change on the inside. And when other people see that change, it helps them know God too!",
        older: "The pastor told a story about a young man who had been doing wrong things in secret. When those things came to light, he was really embarrassed. But instead of making excuses or hiding, he went to the people he'd hurt and said, 'I'm sorry. Will you forgive me?' That act of genuine repentance, being really truly sorry and changing, was so powerful that it actually helped someone else come to know Jesus. Real change starts on the inside.",
        family: "This is the sermon's landing point. A young man's hidden life was exposed. He was humiliated, but he chose repentance over performance. He went back to the people he'd hurt and asked forgiveness. Years later, a woman shared that his act of genuine repentance was the single thing that drew her to faith. Not a perfect life. Not religious performance. A broken person who was honest about his brokenness and let God's grace do the work. That's the alternative to Pharisee religion: not perfection, but authenticity. Not clean cups, but clean hearts."
      },
      quiz: {
        questions: [
          { question: "What does it mean to repent?", options: ["To hide", "To say you're sorry and really change", "To run away"], correctIndex: 1, explanation: "Repenting means saying sorry to God and really wanting to change with his help!", ageGroup: "young" },
          { question: "Can God change us on the inside?", options: ["No, we stay the same", "Yes! God loves to help us change", "Only on the outside"], correctIndex: 1, explanation: "God loves to change our hearts and make us more like Jesus!", ageGroup: "young" },
          { question: "What was more powerful in the story: the man's mistakes or his repentance?", options: ["His mistakes", "His repentance and asking for forgiveness", "Neither"], correctIndex: 1, explanation: "His honest repentance was so powerful it actually brought someone to faith!", ageGroup: "older" },
          { question: "Why does genuine change come from the inside, not the outside?", options: ["Because the outside doesn't matter", "Because outward change without heart change is just acting", "Because God only sees the inside"], correctIndex: 1, explanation: "Lasting change happens when God transforms our hearts. Everything else follows from that.", ageGroup: "older" },
          { question: "What does this sermon teach us about the relationship between vulnerability and spiritual growth?", options: ["Being vulnerable is weakness", "Honest vulnerability before God and others is where genuine transformation begins", "Keep everything private"], correctIndex: 1, explanation: "The gospel doesn't require perfection. It requires honesty. And from honesty, God brings real change.", ageGroup: "family" },
          { question: "How can our family practice 'inside-out' faith this week?", options: ["By following more rules", "By being honest with each other and with God about where we need to grow", "By looking perfect"], correctIndex: 1, explanation: "Start with honesty. Ask each other: where do I need to grow? Then bring it to God together.", ageGroup: "family" },
        ]
      },
      discussionPrompts: {
        prompts: [
          { question: "What's one thing you'd like God to help change on the inside of your heart this week?", parentTip: "Make this a family activity. Everyone shares one thing. Then pray for each other.", connectionToLife: "This is how we practice inside-out faith as a family." },
          { question: "The sermon says 'We grow in Jesus because he's not the God of the outside. He's the God of the heart.' What does that mean to you?", parentTip: "Let everyone define it in their own words. There's no wrong answer.", connectionToLife: "God isn't keeping score of our performance. He's transforming us from within." },
        ]
      },
    },
  ],
};
